from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


class StateStore(Protocol):
    """Persistence contract consumed by the application service."""

    backend_name: str
    expected_schema_version: int

    def schema_version(self) -> int: ...

    def list_schema_migrations(self) -> list[dict[str, Any]]: ...

    def audit_append_only_guards_enabled(self) -> bool: ...

    def load_users(self) -> list[Any]: ...
    def load_tasks(self) -> list[Any]: ...
    def load_approvals(self) -> list[Any]: ...
    def load_audit_events(self) -> list[Any]: ...
    def load_memory(self) -> list[Any]: ...
    def load_knowledge(self) -> list[Any]: ...
    def load_evaluations(self) -> list[Any]: ...
    def load_agents(self) -> list[Any]: ...
    def load_skills(self) -> list[Any]: ...
    def load_tools(self) -> list[Any]: ...
    def load_tool_runs(self) -> list[Any]: ...
    def load_skill_runs(self) -> list[Any]: ...
    def load_workflow_runs(self) -> list[Any]: ...
    def load_workflow_steps(self) -> list[Any]: ...
    def load_model_usage(self) -> list[Any]: ...
    def load_cost_logs(self) -> list[Any]: ...
    def load_budget_policy(self) -> Any | None: ...
    def load_incidents(self) -> list[Any]: ...
    def load_skill_proposals(self) -> list[Any]: ...
    def load_agent_proposals(self) -> list[Any]: ...
    def load_improvement_proposals(self) -> list[Any]: ...
    def load_github_absorptions(self) -> list[Any]: ...
    def load_backups(self) -> list[Any]: ...
    def load_agent_messages(self) -> list[Any]: ...
    def load_agent_meetings(self) -> list[Any]: ...
    def load_task_handoffs(self) -> list[Any]: ...
    def load_agent_broadcasts(self) -> list[Any]: ...
    def load_agent_conflicts(self) -> list[Any]: ...
    def load_task_reviews(self) -> list[Any]: ...
    def load_strategic_goals(self) -> list[Any]: ...
    def load_domain_events(self) -> list[Any]: ...
    def load_scheduled_jobs(self) -> list[Any]: ...
    def load_scheduled_executions(self) -> list[Any]: ...
    def load_chat_sessions(self) -> list[Any]: ...

    def delete_chat_session(self, session_id: str) -> None: ...

    def sync_state(self, **state: Any) -> None: ...

    def restore_snapshot(
        self,
        snapshot: dict[str, Any],
        *,
        approval_id: str,
        backup_id: str,
        actor_id: str,
        safety_backup_id: str,
    ) -> dict[str, int]: ...


@runtime_checkable
class KnowledgeVectorStore(Protocol):
    def list_knowledge_embedding_doc_ids(self) -> set[str]: ...

    def upsert_knowledge_embedding(
        self,
        doc_id: str,
        embedding: list[float],
        metadata: dict[str, Any] | None = None,
    ) -> None: ...

    def search_knowledge_embeddings(
        self, embedding: list[float], *, limit: int = 10
    ) -> list[dict[str, Any]]: ...
